---
esphome:
  name: esp32cam1
  friendly_name: ESP32 Camera 1

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_api_password

# Enable over-the-air updates
ota:
  - platform: esphome
    password: !secret esphome_ota_password

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
#   ap:
#     ssid: "ESP32Cam1-Fallback"
#     password: "esp32cam123"

# captive_portal:

# ESP32 Camera Web Server - snapshot mode only
esp32_camera_web_server:
  - port: 8081
    mode: snapshot
# ESP32 Camera configuration
# camera pinout image at references/ESP32S3_Pinout.png
esp32_camera:
  name: "ESP32 Camera 1"
  external_clock:
    pin: GPIO15
    # frequency: 20MHz
  i2c_pins:
    sda: GPIO4
    scl: GPIO5
  data_pins:
    - GPIO11
    - GPIO9
    - GPIO8
    - GPIO10
    - GPIO12
    - GPIO18
    - GPIO17
    - GPIO16
  vsync_pin: GPIO6
  href_pin: GPIO7
  pixel_clock_pin: GPIO13
  # power_down_pin: GPIO21
  # Camera settings
  resolution: 1920x1080
  jpeg_quality: 20
  vertical_flip: true
  horizontal_mirror: true
  max_framerate: 10fps
  idle_framerate: 0.1fps
  brightness: 2

# Optional: Flash LED for better lighting
# output:
#   - platform: ledc
#     id: camera_flash
#     pin: GPIO47
#     frequency: 1000Hz

# Status LED and Flash LED
light:
  - platform: status_led
    name: "Status LED"
    pin: GPIO48

  # - platform: monochromatic
  #   output: camera_flash
  #   name: "Camera Flash"
  #   id: flash_light
# Button for manual testing (optional)
# button:
#   - platform: template
#     name: "Take Photo"
#     icon: mdi:camera
#     on_press:
#       then:
#         - logger.log: "Taking photo"
#         - light.turn_on:
#             id: flash_light
#             brightness: 100%
#         - delay: 100ms
#         - light.turn_off: flash_light

# Sensors for monitoring
# sensor:
#   - platform: wifi_signal
#     name: "WiFi Signal"
#     update_interval: 60s

#   - platform: uptime
#     name: "Uptime"

# text_sensor:
#   - platform: wifi_info
#     ip_address:
#       name: "IP Address"
#     ssid:
#       name: "Connected SSID"

psram:
  mode: octal
